"""Added required tables

Revision ID: c768c10e81a5
Revises: 
Create Date: 2021-09-11 20:04:16.243100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c768c10e81a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('population_of_countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=30), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('continent', sa.String(length=30), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('population_of_countries')
    # ### end Alembic commands ###
